output "tenant_id" {
    description             = "Value generated by the provider to uniquely identify a PoD"
    value                   = var.prov == "CML" ? module.tenant_cml.0.cust_router_id : ""
}

output "tenant_vrf" {
    description             = "Value generated by the provider to uniquely identify a tenant vrf"
    value                   = var.prov == "CML" ? module.tenant_cml.0.cust_router_name : ""
}

output "tenant_vnet" {
    description             = "Value containing the Azure tenant vnet_id"
    value                   = var.prov == "Azure" ? module.tenant_azure.0.cust-tenant_vnet : null
}

output "cust-tenant-systems_subnet" {
    description             = "Value containing the Azure tenant systems subnet_id"
    value                   = var.prov == "Azure" ? module.tenant_azure.0.cust-tenant-systems_subnet : null
}

output "cust-tenant-systems_subnet_id" {
    description             = "Value containing the Azure tenant systems subnet_id"
    value                   = var.prov == "Azure" ? module.tenant_azure.0.cust-tenant-systems_subnet_id : ""
}