output "compartment_id" {
    description             = "Value generated by CML to uniquely identify an unmanaged VLAN switch"
    value                   = cml2_node.compartment.id
}

output "compartment_name" {
    description             = "Value generated by CML to uniquely identify an unmanaged VLAN switch"
    value                   = var.name
}
