output "lab_id" {
    description             = "Value generated by CML to uniquely identify a lab"
    value                   = cml2_lab.AppPoDSim.id 
}

output "fabric_id" {
    description             = "Value generated by CML to uniquely identify the fabric switch"
    value                   = cml2_node.fabric.id 
}

output "oob_id" {
    description             = "Value generated by CML to uniquely identify the oob switch"
    value                   = cml2_node.oob.id 
}