output "compartment_id" {
    description             = "Value generated by the provider to uniquely identify a compartment"
    value                   = var.prov == "CML" ? module.compartment_cml.0.compartment_id : var.prov == "Azure" ? module.compartment_azure.0.compartment_types_and_asgs.id : null
}

output "compartment_name" {
    description             = "Value generated by the provider to uniquely identify a compartment"
    value                   = var.prov == "CML" ? module.compartment_cml.0.compartment_name : var.prov == "Azure" ? module.compartment_azure.0.compartment_name : null
}

output "compartment_index" {
    description             = "index of compartment"
    value                   = var.y
}

output "compartment_key" {
    description             = "key of compartment"
    value                   = var.key
}

output "compartment_type" {
    description             = "Type of compartment"
    value                   = var.ctype
}
